FROM python:3.12-slim

ENV PYTHONDONTWRITEBYTECODE=1 \
    PYTHONUNBUFFERED=1 \
    TRISMEGISTUS_HOST=0.0.0.0 \
    TRISMEGISTUS_NO_OPEN=1 \
    TRISMEGISTUS_HOSTED_DEMO=1 \
    TRISMEGISTUS_ENABLE_OPENCLAW=0 \
    TRISMEGISTUS_MODEL_TIMEOUT_SECONDS=8 \
    HERMES_TIMEOUT_SECONDS=20

WORKDIR /app

COPY . .

EXPOSE 10000

CMD ["python", "-m", "trismegistus.app"]
